before_install: git clone https://github.com/VincentBlouin/travis-maven-deploy.git
  target/travis
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml
  || mvn clean verify --settings target/travis/settings.xml"
branches:
  only:
  - master
env:
  global:

after_success:
- git clone https://github.com/VincentBlouin/travis-build-children target/travis-build-children
- chmod 755 target/travis-build-children/build_children.sh
- target/travis-build-children/build_children.sh VincentBlouin/bubl.guru_search
